### PR TITLE
securityscanutils: Only scan the latest patch version for a given minor release

### PR DESCRIPTION
**Pull request by nfuden**
Make sec gen less noisy and faster
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/478

### CODE REVIEW

**Comment by nfuden** [comment]
Question: Do we feel that this should be gated with a flag? 
I think not as there is as far as I can tell no valid reason to be scanning old versions at least with how we handle cves but I defer to the reviewer.

**Comment by jackstine** [comment]
> Question: Do we feel that this should be gated with a flag? I think not as there is as far as I can tell no valid reason to be scanning old versions at least with how we handle cves but I defer to the reviewer.

I think that having a flag would still defeat the purpose of the issue that was initially raised. I do not think we need a flag. 

The code LGTM

**Review by bewebi — COMMENTED** [review]
IMO it would be more efficient and probably cleaner to sort `partialFilteredReleases`, then iterate through and add the first release for each minor version we see to `filteredReleases`

Separately, I'm wondering how/if you verified correct behavior? No need for automated tests, but a manual test at least would be good

**Comment by nfuden** [comment]
I thought about doing that but then was annoyed with the major minor combo check. Ill throw it in.

I verified it via gloo with a go workspace. Ill do the same with the new format of using a slice.

**Comment by nfuden** [comment]
Sooooo can has review?

**Review by bewebi — APPROVED** [review]
LGTM

**Pull request merged**
